package eu.buney.sample

/**
 * Public accessor for the Google Maps API key set in `secrets.properties` and generated by
 * BuildKonfig. The BuildKonfig-generated `BuildKonfig` object is `internal`, so this wrapper
 * lets sibling sample modules (`:sample:webApp`) read the key without each having to
 * configure BuildKonfig independently.
 */
fun mapsApiKey(): String = BuildKonfig.MAPS_API_KEY
