package eu.buney.sample

import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.window.ComposeViewport
import eu.buney.maps.MapsConfig
import kotlinx.browser.document

@OptIn(ExperimentalComposeUiApi::class)
fun main() {
    // Configure the Maps JS API key before any GoogleMap composable runs. The key is
    // generated by BuildKonfig from secrets.properties — see README "Web setup".
    MapsConfig.apiKey = mapsApiKey()
    ComposeViewport(document.body!!) {
        App()
    }
}
